#!/usr/bin/env perl
#
# updated at Aug 26, 2026

# Please note that this script is primarily generated by Deepseek-v4-pro and has only been tested and updated using a limited number of samples. 
# The tool will be integrated into GSAT after completing more robust testing.
# Dependencies: perl (5.10+; core modules only), minimap2 (must be installed and reachable via PATH or -m)

use strict;
use warnings;
use Getopt::Long;
use Cwd qw(abs_path);

my $VERSION = "1.1";

# ---------- argument parsing ----------
my ($gfa, $ref, $out, $mm, $threads) = (undef, undef, undef, undef, 8);
my ($min_len, $min_id, $min_cov) = (100, 0.90, 0);
my $mode    = "component";
my $radius  = undef;
my $verbose = 0;
my $help    = 0;

GetOptions(
  "g|gfa=s"       => \$gfa,
  "r|ref=s"       => \$ref,
  "o|out=s"       => \$out,
  "m|minimap2=s"  => \$mm,
  "t|threads=i"   => \$threads,
  "min-len=i"     => \$min_len,
  "min-id=f"      => \$min_id,
  "min-cov=f"     => \$min_cov,
  "mode=s"        => \$mode,
  "radius=i"      => \$radius,
  "v|verbose"     => \$verbose,
  "h|help"        => \$help,
) or die usage();

if ($help) { print usage(); exit 0; }
die usage() unless defined $gfa && defined $ref;

if (defined $radius) { $mode = "radius:$radius"; }

# ---------- argument and input pre-checks ----------
die "ERROR: --threads must be a positive integer (got: $threads)\n"   if $threads !~ /^\d+$/ || $threads < 1;
die "ERROR: --min-len must be a positive integer (got: $min_len)\n"   if $min_len !~ /^\d+$/ || $min_len < 1;
die "ERROR: --min-id must be between 0 and 1 (got: $min_id)\n"        if $min_id  < 0 || $min_id  > 1;
die "ERROR: --min-cov must be between 0 and 1 (got: $min_cov)\n"      if $min_cov < 0 || $min_cov > 1;
die "ERROR: unrecognized --mode: $mode (expected component / induced / radius:N)\n"
  unless $mode =~ /^(component|induced|radius:\d+)$/i;

die "ERROR: GFA file does not exist: $gfa\n"          unless -e $gfa;
die "ERROR: GFA file is not readable: $gfa\n"         unless -r $gfa;
die "ERROR: reference FASTA does not exist: $ref\n"   unless -e $ref;
die "ERROR: reference FASTA is not readable: $ref\n"  unless -r $ref;

# default output name, and guard against overwriting the input GFA
unless (defined $out) {
  ($out = $gfa) =~ s/\.gfa$//i;
  $out .= ".anchored.gfa";
}
my $gfa_abs = abs_path($gfa) || $gfa;
my $out_abs = abs_path($out) || $out;
die "ERROR: output file is the same as the input GFA; refusing to overwrite input: $out\n"
  if $gfa_abs eq $out_abs;

# verify the minimap2 path before invoking any external tool; fail immediately if not found
$mm = resolve_minimap2($mm);
print STDERR "[INFO] minimap2: $mm\n" if $verbose;

# ---------- 1. read the GFA ----------
my %seg;          # id => [seq, original line]
my @links;        # [from, from_orient, to, to_orient, overlap, original line]
my %adj;          # undirected adjacency
my @header;       # H lines
my @paths;        # P / W lines (stored verbatim, filtered at output time)
my @containments; # C lines (stored verbatim, filtered at output time)
my %unknown;      # unrecognized record type => count

open(my $GF, "<", $gfa) or die "ERROR: cannot open GFA file: $gfa ($!)\n";
while (my $line = <$GF>) {
  $line =~ s/[\r\n]+$//;
  next if $line =~ /^\s*$/;
  my @c = split /\t/, $line;

  if    ($c[0] eq "S") {
    if (exists $seg{$c[1]}) { warn "[WARNING] duplicate segment definition, keeping the last one: $c[1]\n"; }
    die "ERROR: segment name contains whitespace and cannot be used as a FASTA header: [$c[1]]\n"
      if $c[1] =~ /\s/;
    $seg{$c[1]} = [ $c[2], $line ];
  }
  elsif ($c[0] eq "L") {
    my $rec = [ $c[1], $c[2], $c[3], $c[4], (defined $c[5] ? $c[5] : "*"), $line ];
    push @links, $rec;
    push @{$adj{$c[1]}}, $c[3];
    push @{$adj{$c[3]}}, $c[1];
  }
  elsif ($c[0] eq "H") { push @header, $line; }
  elsif ($c[0] eq "P" || $c[0] eq "W") { push @paths, $line; }
  elsif ($c[0] eq "C") { push @containments, $line; }
  else { $unknown{$c[0]}++; }
}
close $GF;

my $n_seg = scalar(keys %seg);
my $n_lnk = scalar(@links);
die "ERROR: the GFA contains no segment (S) lines, please check the input file: $gfa\n" if $n_seg == 0;

my $n_dangling = grep { !exists $seg{$_->[0]} || !exists $seg{$_->[2]} } @links;
warn "[WARNING] $n_dangling L line(s) reference segment(s) that do not exist\n" if $n_dangling;
for my $t (sort keys %unknown) {
  warn "[WARNING] record type [$t] ($unknown{$t} line(s)) in the input GFA is not recognized and will not appear in the output\n";
}

# ---------- 2. export segment FASTA and run minimap2 ----------
my $segfa = "$out.segments.fa";
my $paf   = "$out.aln.paf";

open(my $SF, ">", $segfa) or die "ERROR: cannot write $segfa ($!)\n";
for my $id (keys %seg) {
  print $SF ">$id\n$seg{$id}[0]\n";
}
close $SF;

my @cmd = ($mm, "--cs", "-x", "sr", "-t", $threads, "-o", $paf, $segfa, $ref);
print STDERR "[RUN] ", join(" ", @cmd), "\n" if $verbose;

my $rc = system(@cmd);
if ($rc == -1) {
  die "ERROR: failed to start minimap2 process: $mm\n";
}
if ($rc & 127) {
  die sprintf("ERROR: minimap2 was killed by signal %d: %s\n", $rc & 127, join(" ", @cmd));
}
if (($rc >> 8) != 0) {
  die sprintf("ERROR: minimap2 failed (exit code %d): %s\nPlease check minimap2 and the input files.\n",
              $rc >> 8, join(" ", @cmd));
}

# ---------- 3. parse the PAF and determine anchor nodes ----------
my %anchor;                        # anchor segment id => 1
my %q_hit;                         # query => number of records passing thresholds
my %q_any;                         # query => number of all records
my ($rec_total, $rec_pass, $rec_reject, $n_malformed) = (0, 0, 0, 0);

open(my $PF, "<", $paf) or die "ERROR: cannot open alignment result $paf ($!)\n";
while (my $line = <$PF>) {
  chomp $line;
  next if $line =~ /^\s*$/;
  my @c = split /\t/, $line;
  if (@c < 12) { $n_malformed++; next; }

  my ($qname, $tname, $tlen, $ts, $te, $nm, $alen) = @c[0, 5, 6, 7, 8, 9, 10];
  $rec_total++;
  $q_any{$qname}++;

  # cs tag (columns 12 onward)
  my $cs;
  for my $i (12 .. $#c) {
    if ($c[$i] =~ /^cs:Z:(.*)$/) { $cs = $1; last; }
  }

  # identity: prefer cs-based; fall back to nmatch/alen when cs is absent
  my $ident = defined $cs ? cs_identity($cs)
             : ($alen > 0 ? $nm / $alen : 0);

  # target segment coverage fraction
  my $cov = ($tlen > 0) ? ($te - $ts) / $tlen : 0;

  if ($nm >= $min_len && $ident >= $min_id && $cov >= $min_cov) {
    $anchor{$tname} = 1;
    $q_hit{$qname}++;
    $rec_pass++;
  } else {
    $rec_reject++;
  }
}
close $PF;

warn "[WARNING] $n_malformed PAF line(s) with fewer than 12 columns were ignored\n" if $n_malformed;

my $n_anchor = scalar(keys %anchor);
die "ERROR: no segment passed the anchoring thresholds.\n",
    "records: $rec_total, passed: $rec_pass, rejected: $rec_reject.\n",
    "Consider relaxing --min-len/--min-id/--min-cov.\n"
  if $n_anchor == 0;

# ---------- 4. determine the node set to keep according to the mode ----------
my %keep;

if ($mode =~ /^component$/i) {
  # component mode: keep every component that contains at least one anchor
  my %seen;
  for my $start (keys %seg) {
    next if $seen{$start};
    my @q = ($start); $seen{$start} = 1;
    my @comp; my $has_anchor = 0;
    while (@q) {
      my $x = pop @q;
      push @comp, $x;
      $has_anchor = 1 if $anchor{$x};
      for my $y (@{$adj{$x} || []}) {
        unless ($seen{$y}) { $seen{$y} = 1; push @q, $y; }
      }
    }
    if ($has_anchor) { $keep{$_} = 1 for @comp; }
  }
}
elsif ($mode =~ /^induced$/i) {
  %keep = %anchor;
}
elsif ($mode =~ /^radius:(\d+)$/i) {
  # BFS up to R steps from all anchors simultaneously
  my $R = $1;
  my %dist;
  my @q = keys %anchor;
  for my $a (@q) { $dist{$a} = 0; $keep{$a} = 1; }
  while (@q) {
    my $x = shift @q;
    last if $dist{$x} >= $R;
    for my $y (@{$adj{$x} || []}) {
      unless (defined $dist{$y}) {
        $dist{$y} = $dist{$x} + 1;
        $keep{$y} = 1;
        push @q, $y;
      }
    }
  }
}
else {
  # normally intercepted by the pre-check; kept only as a fallback
  die "ERROR: unrecognized --mode: $mode (expected component / induced / radius:N)\n";
}

# ---------- 5. write the new GFA ----------
open(my $OF, ">", $out) or die "ERROR: cannot write $out ($!)\n";
print $OF "$_\n" for @header;

my ($n_keep_seg, $bp_keep) = (0, 0);
for my $id (sort by_id keys %seg) {
  next unless $keep{$id};
  print $OF $seg{$id}[1], "\n";
  $n_keep_seg++;
  $bp_keep += length($seg{$id}[0]);
}

my $n_keep_lnk = 0;
for my $l (@links) {
  next unless $keep{$l->[0]} && $keep{$l->[2]};
  print $OF $l->[5], "\n";
  $n_keep_lnk++;
}

# P/W lines: keep only when all referenced segments are retained
for my $p (@paths) {
  my @c = split /\t/, $p;
  my @ids;
  if ($c[0] eq "P") {
    @ids = map { s/[+-]$//; $_ } split /,/, $c[2];
  } elsif ($c[0] eq "W" && @c > 5) {
    @ids = grep { $_ ne "" } split /[<>]/, $c[5];
  }
  my $all = @ids ? 1 : 0;
  for my $i (@ids) { $all = 0, last unless $keep{$i}; }
  print $OF "$p\n" if $all;
}

# C lines: keep only when both endpoints are retained
for my $o (@containments) {
  my @c = split /\t/, $o;
  print $OF "$o\n" if $keep{$c[1]} && $keep{$c[3]};
}
close $OF;

# ---------- 6. statistics ----------
my $total_bp = 0;
$total_bp += length($seg{$_}[0]) for keys %seg;

print STDERR "========== anchor_subgraph results ==========\n";
print STDERR "minimap2      : $mm\n";
print STDERR "input GFA     : $gfa\n";
print STDERR "  segments(S) : $n_seg ($total_bp bp)\n";
print STDERR "  links(L)    : $n_lnk\n";
print STDERR "reference     : $ref\n";
print STDERR "alignments    : $rec_total total; $rec_pass passed thresholds; $rec_reject rejected\n";
print STDERR "anchor nodes  : $n_anchor\n";
print STDERR "retention mode: $mode\n";
print STDERR "output GFA    : $out\n";
print STDERR "  kept nodes  : $n_keep_seg ($bp_keep bp)\n";
print STDERR "  kept edges  : $n_keep_lnk\n";

print STDERR "anchor records per reference sequence:\n" if $verbose;
for my $q (sort keys %q_any) {
  my $n = $q_hit{$q} || 0;
  if ($n == 0) {
    warn "[WARNING] reference sequence [$q] has no alignment passing the thresholds ($q_any{$q} raw record(s)).\n";
  }
  printf STDERR "  %-40s anchored %d\n", substr($q, 0, 40), $n if $verbose;
}

print STDERR "intermediate files (kept): $segfa, $paf\n";
print STDERR "===========================================\n";

exit 0;

# ==================== subroutines ====================

sub usage {
  my $u = <<"EOF";
anchor_subgraph.en.pl v$VERSION - anchor a GFA subgraph via reference alignment and filter the graph

Usage:
  perl anchor_subgraph.en.pl -g graph.gfa -r ref.fa [-o out.gfa] [options]

Required:
  -g, --gfa FILE      input GFA assembly graph
  -r, --ref FILE      reference FASTA (used as the minimap2 query)

Options:
  -o, --out FILE      output GFA (default: <gfa>.anchored.gfa)
  -m, --minimap2 P    path to minimap2 (default: search PATH for minimap2)
  -t, --threads INT   number of threads (default: 8)
  --min-len INT       minimum matching bases for a valid anchor (default: 100)
  --min-id FLOAT      minimum identity (default: 0.90)
  --min-cov FLOAT     minimum fraction of the target segment covered (default: 0 = no limit)
  --mode STR          retention mode: component|induced|radius:N (default: component)
  --radius INT        equivalent to --mode radius:INT
  -v, --verbose       verbose output
  -h, --help          this help

Examples:
  perl anchor_subgraph.en.pl -g og.filtered.gfa -r NH009.test4.m0.gfa.fas -o NH009.sub.gfa
  perl anchor_subgraph.en.pl -g og.filtered.gfa -r ref.fa --mode induced --min-len 200
EOF
  return $u;
}

# Resolve the minimap2 path: verify before invoking; fail immediately if not found
sub resolve_minimap2 {
  my ($given) = @_;
  my @dirs = grep { $_ ne "" } split /:/, ($ENV{PATH} || "");

  if (defined $given) {
    # user-specified path: verify it directly
    if ($given =~ m{/}) {
      die "ERROR: the specified minimap2 path does not exist or is not executable: $given\n"
        unless -x $given;
      return $given;
    }
    # bare name: search PATH, then try the current directory
    for my $d (@dirs) {
      my $cand = "$d/$given";
      return $cand if -x $cand;
    }
    return "./$given" if -x $given;
    die "ERROR: cannot find the minimap2 executable in PATH (-m given name: $given).\n",
        "Please install minimap2, or specify its full path with -m.\n";
  }

  # default: search PATH for minimap2
  for my $d (@dirs) {
    my $cand = "$d/minimap2";
    return $cand if -x $cand;
  }
  die "ERROR: minimap2 not found. Please install minimap2, or specify its path with -m /path/to/minimap2.\n";
}

# Node ID sorting: numeric order for all-digit IDs (by length then lexicographic,
# to avoid precision loss with very large integers), lexicographic otherwise
sub by_id {
  my ($a_num, $b_num) = ($a =~ /^\d+$/, $b =~ /^\d+$/);
  if ($a_num && $b_num) {
    return length($a) <=> length($b) || $a cmp $b;
  }
  return $a cmp $b;
}

# Compute identity from a cs tag = matches / (matches + subst + ins + del)
# cs grammar: :N N matches; =seq identical bases; *ab one substitution;
#             +seq insertion; -seq deletion; ~N{L,N} intron
sub cs_identity {
  my ($cs) = @_;
  my ($m, $sub, $ins, $del) = (0, 0, 0, 0);
  while ($cs =~ /\G(?: :(\d+) | =([A-Za-z]+) | \*([A-Za-z]{2}) | \+([A-Za-z]+) | -([A-Za-z]+) | ~(\d+)(?:\{\d+,\d+\})? )/gxc) {
    $m   += defined($1) ? $1 : (defined($2) ? length($2) : 0);
    $sub += 1 if defined($3);
    $ins += length($4) if defined($4);
    $del += length($5) if defined($5);
    # $6 is the intron length, excluded from the identity denominator
  }
  my $total = $m + $sub + $ins + $del;
  return $total > 0 ? $m / $total : 0;
}
